### ISSUE TITLE
Discrepancies within the generated BOM

### ISSUE THREAD

**Issue by kotbehemot53** [SukkoPera/ReSeed#1]
Hello,
I noticed that there are some discrepancies in the generated BOM, between the Mouser product numbers and corresponding component values:

L1: 652-RLB0914-331KL - the code refers to a 330 uH inductor, yet the component value is 100 uH, which would be 652-RLB0914-101KL;

C15: 810-FG28C0G1H470JNT0 - the code refers to a 47pF capacitor, yet the component value is 100pF which would be 810-FG28C0G1H101JNT6;

Q1: 512-BC549CTA - the code refers to a BC549C BJT transistor, yet the component value is a BC547C BJT which would be 512-BC547CBU;

RN1: 652-4609X-1LF-4.7K - the code refers to a 4.7 kOhm resistor array, yet the component value is 3.3 kOhm, which would be 652-4609X-1LF-3.3K.

I am aware that some of these are interchangeable, but I still think that the product numbers given should match the component values in the table, because in its current state it causes confusion when ordering parts by their numbers and checking their values.

**Comment by SukkoPera** [comment]
Thanks for the notice, this will be fixed soon with the release of V1.2 and V2.0.

**Comment by root42** [comment]
Any idea when 2.0 will be released? Or can I use the git version? I want to order a minimal number of boards so I can build 1 or 2 SID cards for my C16 and Plus/4 and ask on Forum64 if anyone else wants a board. Or in other words: is it worth waiting for 2.0?

**Comment by SukkoPera** [comment]
I just need to find the time to prepare the docs and do the proper release, but the PCB you can find on the _devel_ branch is final. I will try in the weekend.

**Comment by SukkoPera** [comment]
@root42 Oh BTW, I have some boards I could sell you if you want :).

**Comment by SukkoPera** [comment]
[V2](https://github.com/SukkoPera/ReSeed/releases/tag/v2) has been released, this should fix all of the inconsistencies.

I have decided not to make a v1.2, so I put a link to this issue in the v1.1 release. Let me precise that:

> L1: 652-RLB0914-331KL - the code refers to a 330 uH inductor, yet the component value is 100 uH, which would be 652-RLB0914-101KL;

Correct value is 100 uH.

> C15: 810-FG28C0G1H470JNT0 - the code refers to a 47pF capacitor, yet the component value is 100pF which would be 810-FG28C0G1H101JNT6;

Correct value is 100 pF.

> Q1: 512-BC549CTA - the code refers to a BC549C BJT transistor, yet the component value is a BC547C BJT which would be 512-BC547CBU;

Both can be used. BC549C is recommended as it is the low-noise version, but 547 (and 548, for the record) will work, too.

> RN1: 652-4609X-1LF-4.7K - the code refers to a 4.7 kOhm resistor array, yet the component value is 3.3 kOhm, which would be 652-4609X-1LF-3.3K.

Both will work. I recommend 4.7k because it's the value I tested but no worries ;).

@root42 If you want my boards, send me an email. They are gold-plated and beveled.
