### ISSUE TITLE
Expanding the readme with information on how to prepare the GAL chip

### ISSUE THREAD

**Issue by kotbehemot53** [SukkoPera/ReSeed#2]
While building my ReSeed, I noticed that there was no info about what the GAL chip is and that it needs to be programmed before use. It might be obvious to some people, but not necessarily to every hobbyist. Therefore, I suggest adding a paragraph in the readme with some basic information.

I wanted to create my own branch and make a PR, but I didn't have sufficient permissions, so I'll paste my suggested paragraph here:

```
#### Programming U4 (the GAL chip)

U4 is a Programmable Logic Device or PLD, which means that it is not enough to just connect it to the board - it has to be programmed before use. The necessary .jed file storing the GAL's configuration is provided in the sources in the `gal` directory. To program the chip with the configuration provided, you need to use a programmer. You can build one yourself thanks to the `afterburner` project: https://github.com/ole00/afterburner. There is a simpler variant of the afterburner device (https://github.com/ole00/afterburner/tree/version_4_legacy) which is sufficient and can easily be built on a breadbord. A tutorial on how to do this is available here: https://www.instructables.com/Make-Your-Own-Microchips/.
```

I suggest adding the above paragraph as part of the `Integrated circuits` section.

**Comment by SukkoPera** [comment]
Good idea, will do.

PS: You should be able to fork the repo, there is no special protection and no permission requirements.

**Comment by SukkoPera** [comment]
I decided to move the assembly instructions to the Wiki and, while doing that, I integrated your suggestion. Please check if it is clearer now: https://github.com/SukkoPera/ReSeed/wiki/V1.x-Assembly-Notes.

**Comment by kotbehemot53** [comment]
Looks great, cheers!
