### ISSUE TITLE
R3 ambiguity between V2 assembly notes and BOM notes

### ISSUE THREAD

**Issue by SteveGuidi** [SukkoPera/ReSeed#3]
In the [V2 assembly notes](https://github.com/SukkoPera/ReSeed/wiki/V2-Assembly-Notes), we are directed to not mount R3 for an 8580 build.  However, the [notes in the BOM](https://github.com/SukkoPera/ReSeed/releases/download/v2/ReSeed-2-ibom.html) state that we should not mount R3 for a 6581 build.

**Comment by SukkoPera** [comment]
I am under the impression I have already fixed this, but anyway the assembly notes are correct.

No big deal in any case, just a decrease in output volume.

**Comment by SukkoPera** [comment]
BOM on release page updated.
